### ISSUE TITLE
storage: multipart primary keys

### ISSUE THREAD

**Issue by fdymylja** [CosmWasm/cosmwasm-go#124]
We need to also be capable of supporting objects in which multiple fields are primary keys.

Example:

```go
type Balance struct {
    Address string <- primary key part 1
    Denom string <- primary key part 2
    Amount math.Uint128
}
```

It's not urgent as once indexing by fields is implemented this behaviour can be achieved (with a little of machinery - you need an intermediate object and to compose keys by yourself) without any extra code.

But we still should provide tooling to implement this effortlessly.

**Comment by ethanfrey** [comment]
ORM Moved to archway repo
