### ISSUE TITLE
Thoughts for API enhancements

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cosmwasm-go#136]
Looking at https://github.com/confio/cosmwasm-go/tree/v0.3.1/example/identity as an example. This is actually getting very smooth and concise. 

- [x] [`ExecuteMsg`](https://github.com/confio/cosmwasm-go/blob/v0.3.1/example/identity/src/msgs.go#L19-L24) (union) could be auto-generated if we tag all the variants
- [x] [`Execute` method](https://github.com/confio/cosmwasm-go/blob/v0.3.1/example/identity/src/contract.go#L17-L34) could be auto-generated to dispatch each variant to it's own handlers
- [x] Handling [storage in a method](https://github.com/confio/cosmwasm-go/blob/v0.3.1/example/identity/src/contract.go#L36-L74) works great!
- [x] We could auto-generate [`MsgCreateIdentity{}.Execute()` returns `ExecuteMsg`](https://github.com/confio/cosmwasm-go/blob/v0.3.1/example/identity/src/contract_test.go#L24-L29) for easier test calls
- [x] [En/de-coding and querying](https://github.com/confio/cosmwasm-go/blob/v0.3.1/example/identity/src/contract_test.go#L33-L39) could be simpler (using Msg -> `QueryMsg` as above). Like  [this](https://github.com/confio/cosmwasm-go/blob/v0.3.1/example/identity/src/contract_test.go#L66-L71) or even:
  ```
  identity := new(Person)
  doQuery(t, Query, deps, env, &QueryIdentity{ID: exists})
  ```
- [ ] `systest.Instance` could have [same logic baked in](https://github.com/confio/cosmwasm-go/blob/v0.3.1/example/identity/integration/integration_test.go#L35-L40) 
- [ ] [Helpers for `std.QueryRequest`](https://github.com/confio/cosmwasm-go/issues/105#issuecomment-978172745) and `std.CosmosMsg`

After that, it is just about the tooling and ease of calling the code generators.

**Comment by fdymylja** [comment]
Closing this as it is not relevant anymore
